#ifndef _COMPILER_TOKEN_HH_
#define _COMPILER_TOKEN_HH_

enum Token {
    // 关键词
    IF, ELSE, SWITCH, CASE, DEFAULT, WHILE, FOR, BREAK, CONTINUE, LET, CONST, TRUE, FALSE, NULL, UNDEFINED,

    // 操作符
    ASSIGN, PLUS_ASSIGN, MINUS_ASSIGN, MUL_ASSIGN, DIV_ASSIGN, EXP_ASSIGN, MOD_ASSIGN,
    LOGICAL_OR, LOGICAL_AND,
    EQUAL, NOT_EQUAL,
    LESS_THAN, GREATER_THAN, LESS_EQUAL, GREATER_EQUAL,
    ADD, SUB,
    MUL, DIV, MOD,
    EXP,

    // 一元操作符
    PLUS, MINUS, NOT,

    // 分隔符
    SEMICOLON, COMMA,

    // 括号
    LPAREN, RPAREN, LBRACE, RBRACE, LBRACKET, RBRACKET,

    // 字面量
    IDENTIFIER, STRING_LITERAL, NUMBER_LITERAL,

    // 函数
    ARROW_FUNCTION,

    // 其他
    EOF // 表示文件结束
};

#endif // !_COMPILER_TOKEN_HH_
